<?php
class FilterModel {
	protected $options = null;
	
	function __construct($options){
		$this->options = $options;
	}


	/**
	 * returns a json object of games and their categories
	 */
	public function getGames(){
		$query = new WP_Query(array(
			'post_type' => 'fitness_class',
			'posts_per_page' => 999999
		));
		$ret = array();
		if($query->have_posts()){
			while($query->have_posts()){
				$query->the_post();

				$p = array(
					'title' => get_the_title(),
					'id'=>get_the_ID(),
					'categories'=>get_the_terms(get_the_ID(),'fitness_category') //produces a flat list with parent references
				);
				$ret[] = $p;
			}
		}

		return json_encode($ret);
	}
}


/*
Example data

[
    {
        "title": "i-Skate",
        "id": 13296,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13296,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13296,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13296,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13296,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13296,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13296,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13296,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13296,
                "filter": "raw"
            },
            "119": {
                "term_id": 119,
                "name": "1 persoon",
                "slug": "1-persoon",
                "term_group": 0,
                "term_taxonomy_id": 119,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 20,
                "object_id": 13296,
                "filter": "raw"
            },
            "120": {
                "term_id": 120,
                "name": "2 personen",
                "slug": "2-personen",
                "term_group": 0,
                "term_taxonomy_id": 120,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 8,
                "object_id": 13296,
                "filter": "raw"
            },
            "121": {
                "term_id": 121,
                "name": "3 - 4 personen",
                "slug": "3-4-personen",
                "term_group": 0,
                "term_taxonomy_id": 121,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 10,
                "object_id": 13296,
                "filter": "raw"
            },
            "122": {
                "term_id": 122,
                "name": "5 of meer personen",
                "slug": "5-of-meer-personen",
                "term_group": 0,
                "term_taxonomy_id": 122,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 5,
                "object_id": 13296,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13296,
                "filter": "raw"
            },
            "124": {
                "term_id": 124,
                "name": "Te huur",
                "slug": "te-huur",
                "term_group": 0,
                "term_taxonomy_id": 124,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 21,
                "object_id": 13296,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13296,
                "filter": "raw"
            },
            "154": {
                "term_id": 154,
                "name": "E-fit zone",
                "slug": "e-fit-zone",
                "term_group": 0,
                "term_taxonomy_id": 154,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 3,
                "object_id": 13296,
                "filter": "raw"
            },
            "176": {
                "term_id": 176,
                "name": "E-fit zone (op aanvraag beschikbaar)",
                "slug": "e-fit-op-aanvraag",
                "term_group": 0,
                "term_taxonomy_id": 176,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 3,
                "object_id": 13296,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Snowboard Game",
        "id": 13486,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13486,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13486,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13486,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13486,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13486,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13486,
                "filter": "raw"
            },
            "120": {
                "term_id": 120,
                "name": "2 personen",
                "slug": "2-personen",
                "term_group": 0,
                "term_taxonomy_id": 120,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 8,
                "object_id": 13486,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13486,
                "filter": "raw"
            },
            "124": {
                "term_id": 124,
                "name": "Te huur",
                "slug": "te-huur",
                "term_group": 0,
                "term_taxonomy_id": 124,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 21,
                "object_id": 13486,
                "filter": "raw"
            },
            "154": {
                "term_id": 154,
                "name": "E-fit zone",
                "slug": "e-fit-zone",
                "term_group": 0,
                "term_taxonomy_id": 154,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 3,
                "object_id": 13486,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Fittests",
        "id": 13480,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13480,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13480,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13480,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13480,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13480,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13480,
                "filter": "raw"
            },
            "119": {
                "term_id": 119,
                "name": "1 persoon",
                "slug": "1-persoon",
                "term_group": 0,
                "term_taxonomy_id": 119,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 20,
                "object_id": 13480,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13480,
                "filter": "raw"
            },
            "124": {
                "term_id": 124,
                "name": "Te huur",
                "slug": "te-huur",
                "term_group": 0,
                "term_taxonomy_id": 124,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 21,
                "object_id": 13480,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13480,
                "filter": "raw"
            },
            "176": {
                "term_id": 176,
                "name": "E-fit zone (op aanvraag beschikbaar)",
                "slug": "e-fit-op-aanvraag",
                "term_group": 0,
                "term_taxonomy_id": 176,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 3,
                "object_id": 13480,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Lightspace",
        "id": 13474,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13474,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13474,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13474,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13474,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13474,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13474,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13474,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13474,
                "filter": "raw"
            },
            "121": {
                "term_id": 121,
                "name": "3 - 4 personen",
                "slug": "3-4-personen",
                "term_group": 0,
                "term_taxonomy_id": 121,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 10,
                "object_id": 13474,
                "filter": "raw"
            },
            "122": {
                "term_id": 122,
                "name": "5 of meer personen",
                "slug": "5-of-meer-personen",
                "term_group": 0,
                "term_taxonomy_id": 122,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 5,
                "object_id": 13474,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13474,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13474,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Electronic Darts",
        "id": 13472,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13472,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13472,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13472,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13472,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13472,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13472,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13472,
                "filter": "raw"
            },
            "120": {
                "term_id": 120,
                "name": "2 personen",
                "slug": "2-personen",
                "term_group": 0,
                "term_taxonomy_id": 120,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 8,
                "object_id": 13472,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13472,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13472,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Trailblazer Travers",
        "id": 13467,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13467,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13467,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13467,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13467,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13467,
                "filter": "raw"
            },
            "121": {
                "term_id": 121,
                "name": "3 - 4 personen",
                "slug": "3-4-personen",
                "term_group": 0,
                "term_taxonomy_id": 121,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 10,
                "object_id": 13467,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13467,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13467,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Soundsteps",
        "id": 13463,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13463,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13463,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13463,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13463,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13463,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13463,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13463,
                "filter": "raw"
            },
            "121": {
                "term_id": 121,
                "name": "3 - 4 personen",
                "slug": "3-4-personen",
                "term_group": 0,
                "term_taxonomy_id": 121,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 10,
                "object_id": 13463,
                "filter": "raw"
            },
            "122": {
                "term_id": 122,
                "name": "5 of meer personen",
                "slug": "5-of-meer-personen",
                "term_group": 0,
                "term_taxonomy_id": 122,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 5,
                "object_id": 13463,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13463,
                "filter": "raw"
            },
            "124": {
                "term_id": 124,
                "name": "Te huur",
                "slug": "te-huur",
                "term_group": 0,
                "term_taxonomy_id": 124,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 21,
                "object_id": 13463,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Jump Q",
        "id": 13459,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13459,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13459,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13459,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13459,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13459,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13459,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13459,
                "filter": "raw"
            },
            "119": {
                "term_id": 119,
                "name": "1 persoon",
                "slug": "1-persoon",
                "term_group": 0,
                "term_taxonomy_id": 119,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 20,
                "object_id": 13459,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13459,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13459,
                "filter": "raw"
            }
        }
    },
    {
        "title": "Heavy Ball",
        "id": 13455,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13455,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13455,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13455,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13455,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13455,
                "filter": "raw"
            },
            "119": {
                "term_id": 119,
                "name": "1 persoon",
                "slug": "1-persoon",
                "term_group": 0,
                "term_taxonomy_id": 119,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 20,
                "object_id": 13455,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13455,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13455,
                "filter": "raw"
            }
        }
    },
    {
        "title": "3 Kick",
        "id": 13450,
        "categories": {
            "111": {
                "term_id": 111,
                "name": "Beweeggames",
                "slug": "beweeggames",
                "term_group": 0,
                "term_taxonomy_id": 111,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13450,
                "filter": "raw"
            },
            "112": {
                "term_id": 112,
                "name": "Geschikt voor",
                "slug": "geschikt-voor",
                "term_group": 0,
                "term_taxonomy_id": 112,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13450,
                "filter": "raw"
            },
            "113": {
                "term_id": 113,
                "name": "Jongeren",
                "slug": "jongeren",
                "term_group": 0,
                "term_taxonomy_id": 113,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 30,
                "object_id": 13450,
                "filter": "raw"
            },
            "114": {
                "term_id": 114,
                "name": "Kinderen",
                "slug": "kinderen",
                "term_group": 0,
                "term_taxonomy_id": 114,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 25,
                "object_id": 13450,
                "filter": "raw"
            },
            "115": {
                "term_id": 115,
                "name": "Volwassenen",
                "slug": "volwassenen",
                "term_group": 0,
                "term_taxonomy_id": 115,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 28,
                "object_id": 13450,
                "filter": "raw"
            },
            "116": {
                "term_id": 116,
                "name": "Mensen met een verstandelijke beperking",
                "slug": "verstandelijke-beperking",
                "term_group": 0,
                "term_taxonomy_id": 116,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13450,
                "filter": "raw"
            },
            "117": {
                "term_id": 117,
                "name": "Ouderen",
                "slug": "ouderen",
                "term_group": 0,
                "term_taxonomy_id": 117,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 112,
                "count": 27,
                "object_id": 13450,
                "filter": "raw"
            },
            "118": {
                "term_id": 118,
                "name": "Aantal personen",
                "slug": "aantal-personen",
                "term_group": 0,
                "term_taxonomy_id": 118,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13450,
                "filter": "raw"
            },
            "119": {
                "term_id": 119,
                "name": "1 persoon",
                "slug": "1-persoon",
                "term_group": 0,
                "term_taxonomy_id": 119,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 118,
                "count": 20,
                "object_id": 13450,
                "filter": "raw"
            },
            "123": {
                "term_id": 123,
                "name": "Huur of koop?",
                "slug": "huur-of-koop",
                "term_group": 0,
                "term_taxonomy_id": 123,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 0,
                "count": 34,
                "object_id": 13450,
                "filter": "raw"
            },
            "125": {
                "term_id": 125,
                "name": "Te koop",
                "slug": "te-koop",
                "term_group": 0,
                "term_taxonomy_id": 125,
                "taxonomy": "fitness_category",
                "description": "",
                "parent": 123,
                "count": 17,
                "object_id": 13450,
                "filter": "raw"
            }
        }
    }
]
 */
?>
